# This file was generated by GoReleaser. DO NOT EDIT.
cask "dx-prerelease" do
  name "dx-prerelease"
  desc "DX is a tool for managing a local development environment using kubernetes (prerelease)"
  homepage "https://henriq.se/"
  version "1.1.1-prerelease+e4f0fdff"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dx"
  bash_completion "completions/dx.bash"
  zsh_completion "completions/dx.zsh"
  fish_completion "completions/dx.fish"

  on_macos do
    on_intel do
      url "https://github.com/henriq/dx/releases/download/v#{version}/dx_Darwin_x86_64.tar.gz"
      sha256 "7148bc203e77ea298923d4f423d2a70cbebb9181c1ded6ca5cf2585ebe690fb6"
    end
    on_arm do
      url "https://github.com/henriq/dx/releases/download/v#{version}/dx_Darwin_arm64.tar.gz"
      sha256 "fef70a61386bacc3c846177b6177f46d37c505ef2e8289e7b12e6ec3ed72d1ef"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/henriq/dx/releases/download/v#{version}/dx_Linux_x86_64.tar.gz"
      sha256 "e75f84134285f0c5d307912e3782ee1d1c197fe4439a0df419da0046313c576e"
    end
    on_arm do
      url "https://github.com/henriq/dx/releases/download/v#{version}/dx_Linux_arm64.tar.gz"
      sha256 "d640335ac8467ace434ba5bc0124d04b7fcc22c3474ae776c9a8abf2d35877a3"
    end
  end

  conflicts_with cask: [
      "dx",
    ]

  # No zap stanza required
end
