# This file was generated by GoReleaser. DO NOT EDIT.
cask "dx-prerelease" do
  version "1.5.10-prerelease+326f980b"

  on_macos do
    on_intel do
      url "https://github.com/henriq/dx/releases/download/v#{version}/dx_Darwin_x86_64.tar.gz"
      sha256 "42fd065ba29469c6010ce2f334c0b15d1e3acc7055d22c16cffc1ef6c78bf186"
    end
    on_arm do
      url "https://github.com/henriq/dx/releases/download/v#{version}/dx_Darwin_arm64.tar.gz"
      sha256 "e0a618938acbb3374ace486840439a3c3f6d1d20bf58149c5f9b0d224ca13e18"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/henriq/dx/releases/download/v#{version}/dx_Linux_x86_64.tar.gz"
      sha256 "193a1c91f4d1e16a784f399722ddf399aac0538658f2eb73d83832f9660578d8"
    end
    on_arm do
      url "https://github.com/henriq/dx/releases/download/v#{version}/dx_Linux_arm64.tar.gz"
      sha256 "af28054c57d5e244fb48df192d23991eac66aa1b19fbd31559076c4b1dd16e0d"
    end
  end

  name "dx-prerelease"
  desc "DX is a tool for managing a local development environment using kubernetes (prerelease)"
  homepage "https://henriq.se/"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "dx",
    ]

  binary "dx"

  # No zap stanza required

end
