# This file was generated by GoReleaser. DO NOT EDIT.
cask "dx-prerelease" do
  version "1.5.13-prerelease+ef54a47c"

  on_macos do
    on_intel do
      url "https://github.com/henriq/dx/releases/download/v#{version}/dx_Darwin_x86_64.tar.gz"
      sha256 "5852ea5c195bd9c1fdb212d8842d53e0986d04f0b92f6bb0ca8d5a1711d3c3a4"
    end
    on_arm do
      url "https://github.com/henriq/dx/releases/download/v#{version}/dx_Darwin_arm64.tar.gz"
      sha256 "c8b56e172ed350bc535cc5f8915e278fa4e6c2a8e54ba4995451f4a46c07d101"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/henriq/dx/releases/download/v#{version}/dx_Linux_x86_64.tar.gz"
      sha256 "6cd68ae343f2c3093545ed121c47d20877b5ec1bb2db6c9844373e9999c5e2da"
    end
    on_arm do
      url "https://github.com/henriq/dx/releases/download/v#{version}/dx_Linux_arm64.tar.gz"
      sha256 "91604ea1dcfe85390444f01c6cef45ca86bdd0667d6545b9422d6012d8b05d33"
    end
  end

  name "dx-prerelease"
  desc "DX is a tool for managing a local development environment using kubernetes (prerelease)"
  homepage "https://henriq.se/"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "dx",
    ]

  binary "dx"
  generate_completions_from_executable "dx"

  # No zap stanza required

end
