# This file was generated by GoReleaser. DO NOT EDIT.
cask "dx" do
  name "dx"
  desc "DX is a tool for managing a local development environment using kubernetes"
  homepage "https://henriq.se/"
  version "1.2.16"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dx"

  on_macos do
    on_intel do
      url "https://github.com/henriq/dx/releases/download/v#{version}/dx_Darwin_x86_64.tar.gz"
      sha256 "a5e0d51d194f7c2e348b679d692994f59cbcc49ebe8a9c8118789995bf3d0768"
    end
    on_arm do
      url "https://github.com/henriq/dx/releases/download/v#{version}/dx_Darwin_arm64.tar.gz"
      sha256 "ee1cc3ed3935323ea2a8171a5ab87cf2df55d917cdab503f710fa610eb5c53f3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/henriq/dx/releases/download/v#{version}/dx_Linux_x86_64.tar.gz"
      sha256 "eebb2b4a8527362118e92f0e443d253412c320cf1fc73a8b2426e3067348fe83"
    end
    on_arm do
      url "https://github.com/henriq/dx/releases/download/v#{version}/dx_Linux_arm64.tar.gz"
      sha256 "b6ab816b1ddd121cb92019889c1f852288c7bc5985f2c274d885bd49dddd9b61"
    end
  end

  conflicts_with cask: [
      "dx-prerelease",
    ]

  # No zap stanza required
end
