# This file was generated by GoReleaser. DO NOT EDIT.
cask "dx" do
  version "1.5.15"

  on_macos do
    on_intel do
      url "https://github.com/henriq/dx/releases/download/v#{version}/dx_Darwin_x86_64.tar.gz"
      sha256 "cfb27fc3632ac69fc1626d95fb24dd792e16646a1ac83f0fac338b2cc5e8593e"
    end
    on_arm do
      url "https://github.com/henriq/dx/releases/download/v#{version}/dx_Darwin_arm64.tar.gz"
      sha256 "dbee754d81c17beedf53cf7958f5c61223360a5c8c85c1af63335750773ed505"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/henriq/dx/releases/download/v#{version}/dx_Linux_x86_64.tar.gz"
      sha256 "905a507a546c9d6f8508256b271c51e46e847d9849efb5b53a964383db014e31"
    end
    on_arm do
      url "https://github.com/henriq/dx/releases/download/v#{version}/dx_Linux_arm64.tar.gz"
      sha256 "6453cec192a4812da89764fba7c1fc449cba586bb5289cb7d3c0f00aa0c75af6"
    end
  end

  name "dx"
  desc "DX is a tool for managing a local development environment using kubernetes"
  homepage "https://henriq.se/"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "dx-prerelease",
    ]

  binary "dx"
  generate_completions_from_executable "dx",
    shell_parameter_format: :cobra

  # No zap stanza required

end
