# This file was generated by GoReleaser. DO NOT EDIT.
cask "dx" do
  name "dx"
  desc "DX is a tool for managing a local development environment using kubernetes"
  homepage "https://henriq.se/"
  version "1.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dx"
  bash_completion "completions/dx.bash"
  zsh_completion "completions/dx.zsh"
  fish_completion "completions/dx.fish"

  on_macos do
    on_intel do
      url "https://github.com/henriq/dx/releases/download/v#{version}/dx_Darwin_x86_64.tar.gz"
      sha256 "e916d0480a2dc3a13e0de5eb846e4f742ecb45127e57a91f6340239522da0b13"
    end
    on_arm do
      url "https://github.com/henriq/dx/releases/download/v#{version}/dx_Darwin_arm64.tar.gz"
      sha256 "7bb986be23ac175cd587b239448c2ca0c2f8edf83fa1da43fe525c9b13c5b55c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/henriq/dx/releases/download/v#{version}/dx_Linux_x86_64.tar.gz"
      sha256 "794499fbfde23e2258926b2001bcb3d97206066d2139d7d982652e94a338564c"
    end
    on_arm do
      url "https://github.com/henriq/dx/releases/download/v#{version}/dx_Linux_arm64.tar.gz"
      sha256 "745fbf08f7aacbe7db18315ae19547acfc8865ae086798795e51dd2f196a60fc"
    end
  end

  conflicts_with cask: [
      "dx-prerelease",
    ]

  # No zap stanza required
end
