# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DxPrerelease < Formula
  desc "DX is a tool for managing a local development environment using kubernetes (prerelease)"
  homepage "https://henriq.se/"
  version "0.1.4-prerelease+ad15337f"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/henriq/dx/releases/download/v0.1.4-prerelease+ad15337f/dx_Darwin_x86_64.tar.gz"
      sha256 "7086fbd62780834d13516bf8259afc5467c0a2e3f103bfe42179867b7705df02"

      def install
        bin.install "dx"
        bash_completion.install "completions/dx.bash" => "dx"
        zsh_completion.install "completions/dx.zsh" => "_dx"
        fish_completion.install "completions/dx.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/henriq/dx/releases/download/v0.1.4-prerelease+ad15337f/dx_Darwin_arm64.tar.gz"
      sha256 "6b3ab998a7e7a779c183eb2fb3249a4077a3a78063945f937e7ad719933d4150"

      def install
        bin.install "dx"
        bash_completion.install "completions/dx.bash" => "dx"
        zsh_completion.install "completions/dx.zsh" => "_dx"
        fish_completion.install "completions/dx.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/henriq/dx/releases/download/v0.1.4-prerelease+ad15337f/dx_Linux_x86_64.tar.gz"
      sha256 "3b21728cf4879f9ee5eae74ab10a8c4fa5342f118992434d52079f3530a28a85"
      def install
        bin.install "dx"
        bash_completion.install "completions/dx.bash" => "dx"
        zsh_completion.install "completions/dx.zsh" => "_dx"
        fish_completion.install "completions/dx.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/henriq/dx/releases/download/v0.1.4-prerelease+ad15337f/dx_Linux_arm64.tar.gz"
      sha256 "c2e07d9837c09cfdf46338579392195da9847611d0456995ea51c67090a1f670"
      def install
        bin.install "dx"
        bash_completion.install "completions/dx.bash" => "dx"
        zsh_completion.install "completions/dx.zsh" => "_dx"
        fish_completion.install "completions/dx.fish"
      end
    end
  end

  conflicts_with "dx"
end
